config/routes.rb
Rails.application.routes.draw do

  resources :venues
  resources :users
  resources :bookings
  resources :favorites

  get 'partyspace', to: 'login#partyspace', as: 'partyspace'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'login#new', as: 'login'
  delete 'logout', to: 'login#destroy', as: 'logout'

  # get 'logout', to: 'login#destroy', as: 'logout'
  # delete '/logout', to: 'login#destroy', as: :logout

  resources :login, only: [:new, :create, :destroy]


  # root "venues#index"
  root "login#partyspace"

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :get_booking, only: [:show, :edit, :update, :destroy]


  def index
    @bookings = Booking.all
  end

  def show

  end

  def edit

  end

  def update
    booking_params[:total_price] = booking_params[:duration].to_i * booking_params[:total_price].to_i
    @booking.update(booking_params)
    redirect_to @booking
  end

  def new
    @venue = Venue.find(params[:venue_id])
    @booking = Booking.new
  end

  def create
    booking_params[:total_price] = booking_params[:duration].to_i * booking_params[:total_price].to_i
    @booking = Booking.create(booking_params)
    # byebug

    redirect_to @current_user
  end

  def destroy

  end

  private

  def get_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :venue_id, :date, :total_price, :duration)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.erb
<div class="a">

  <h1>List of the person's Bookings</h1>

  <ul style="list-style-type:none;">

    <% @bookings.each do |booking| %>
      <li>
        <a class="venue-img-link" href="/bookings/<%= booking.id %>">
        <img src="<%= booking.venue.img_url %>" alt="<%= booking.venue.name %>" class="center">
        </a>
        <%= booking.venue.name %>
        <br><br>
      </li>
    <% end %>
  </ul>
</div>

app/views/bookings/new.erb
<div class="bgt booking-font">
  <div class="a">
    <br>

    <h1><strong>Book it? <%= @venue.name %>??</strong></h1>

    <ul style="list-style-type:none;">
      <%= form_for @booking do |f| %>
        <li><%= f.label :hours %>
        <%= f.number_field :duration %></li>

        <li><%= f.label :date %>
        <%= f.date_select :date %></li>

        <input type="hidden" name="booking[venue_id]" value="<%= @venue.id %>">
        <input type="hidden" name="booking[user_id]" value="<%= @current_user.id %>">
        <input type="hidden" name="booking[total_price]" value="<%= @venue.price %>">

        <%= f.submit "Book it!", {class: "btn btn-info"} %>
        
      <% end %>
    </ul>
  </div>
</div>

app/views/bookings/show.erb
<div class="a">
<h1><%= @booking.user.name %></h1>

<img src="<%= @booking.venue.img_url %>" alt="<%= @booking.venue.name %>" class="center">
<!-- <section class="jumbotron text-center">
  <div class="container">
  </div>
</section> -->

<h4>
<ul style="list-style-type:none;">
  <li>Location: <%= @booking.venue.location %></li>
  <li>Duration: <%= @booking.duration %></li>
  <li>Price Total: $<%= @booking.total_price %></li>
  <li>Capacity: <%= @booking.venue.capacity %> people</li>
  <li>Activity: <%= @booking.venue.activity %></li>
  <li>Amenities: <%= @booking.venue.amenities.delete('"[]\"').split(",").join(", ") %></li>

  <li>Contact Host: <%= link_to @booking.venue.user.name, @booking.venue.user %></li>
</ul>
</h4>

<%= link_to "Edit", edit_booking_path %>
<br>
<%= link_to "My Bookings", bookings_path %>
</div>
<br><br><br>