config/routes.rb
Rails.application.routes.draw do

  resources :venues
  resources :users
  resources :bookings
  resources :favorites

  get 'partyspace', to: 'login#partyspace', as: 'partyspace'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'login#new', as: 'login'
  delete 'logout', to: 'login#destroy', as: 'logout'

  # get 'logout', to: 'login#destroy', as: 'logout'
  # delete '/logout', to: 'login#destroy', as: :logout

  resources :login, only: [:new, :create, :destroy]


  # root "venues#index"
  root "login#partyspace"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :venues
  has_many :bookings
  has_many :venue_bookings, :through => :bookings, :source => :venue
  has_many :favorites
  has_many :venue_favorites, through: :favorites, source: :venue

  validates :email, { presence: true, uniqueness: true }
  # validates :password, { presence: true }

  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    # byebug
    @user = User.create(user_params)
    if @user.valid?
      login_user(@user)
      redirect_to user_path(@user)
    else
      # flash[:errors] = @user.errors.full_messages
      render :new
      # redirect_to new_user_path
    end
  end

  def edit
  end

  def update
    # raise params.inspect
    # @user.update(name: params[:user][:name], img_url: params[:user][:img_url])
    @user.update(user_params)
    # byebug
    redirect_to user_path(@user)

  end

  def destroy
    @user.destroy
    redirect_to "/partyspace"
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :img_url)
  end

  def get_user
    @user = User.find(params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="a">
<section class="jumbotron text-center">
  <h1>Update <%= @user.name %>'s Profile</h1>
</section>



<ul style="list-style-type:none;">
<%= form_for @user do |f| %>
  <li>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </li>



  <li>
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </li>

  <%= f.submit "Update", {class: "btn btn-outline-secondary"}%>
<% end %>
</ul>
</div>

app/views/users/index.html.erb
<h1>All Users:</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %> <img src="<%= user.img_url %>" style="width:40px;height:40px;">
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="bg-new-user cover-heading">
<div class="a">
<br>
    <h1>Sign Up</h1>



  <% if @user.errors.any? %>

    <h2><%= pluralize(@user.errors.count, "error") %> prohibited your account from being created!</h2>

    <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
<% end %>

<%= form_for @user do |f| %>
  <ul style="list-style-type:none;">
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
    <li>
      <%= f.label :img_url %>
      <%= f.text_field :img_url %>
    </li>
  </ul>
  <%= f.submit class: "btn btn-info" %>
<% end %>



</div>
</div>

app/views/users/show.html.erb
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="album.css" rel="stylesheet">

<!DOCTYPE html>
<html>
  <head>
    <title>User Page</title>
  </head>

  <body>
    <br>

    <h1 class="prof-margin"><%= @user.name %>'s Profile</h1>
    <img src="<%= @user.img_url %>" alt="Avatar" class="avatar">
    <br>
    <br>
    <div class="prof-margin">

      <ul style="list-style-type:none;">
        <li>
          <b>Email: </b><%= @user.email %>
        </li>
      </ul>
      <p><a class="btn btn-outline-secondary" href=/users/<%= @user.id %>/edit role="button">Edit <%= @user.name %> &raquo;</a>
        <a class="btn btn-outline-secondary" href=/users/<%= @user.id %> role="button">Delete <%= @user.name %> &raquo;</a>
      </p>
      <br>
  </div>


    <h3 class="prof-margin">My List</h3>

    <main role="main">
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <% @user.venues.each do |venue| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" src="<%= venue.img_url %>" </img><rect src="<%= venue.img_url %>"width="100%" height="100%" fill="#55595c"/>
              <div class="card-body">
                <p class="card-text"><%= venue.name %>
                </p>
                <%= link_to "View Details", venue, {class:"btn btn-sm btn-outline-secondary"} %>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>

        </div>
      </div>
    </div>
    </main>

<h3 class="prof-margin">Booked</h3>
<main role="main">
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @user.bookings.each do |booking| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" src="<%= booking.venue.img_url %>" </img><rect src="<%= booking.venue.img_url %>"width="100%" height="100%" fill="#55595c"/>
          <div class="card-body">
            <p class="card-text">
            <a style="list-style-type:none;">
                <li style="list-style-type:none;"><b><%= booking.venue.name %></b></li>
                <li>Hours: <%= booking.duration %></li>
                <li>Price: <%= booking.total_price %></li>
              </a>
            </p>
            <%= link_to "View Venue Details", booking.venue, {class:"btn btn-sm btn-outline-secondary"} %>

            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</div>
</main>

<h3 class="prof-margin">Liked</h3>
<main role="main">
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @user.favorites.each do |favorite| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" src="<%= favorite.venue.img_url %>" </img><rect src="<%= favorite.venue.img_url %>"width="100%" height="100%" fill="#55595c"/>
          <div class="card-body">
            <p class="card-text"><%= favorite.venue.name %></p>
            <%= link_to "View Details", favorite.venue, {class:"btn btn-sm btn-outline-secondary"} %>
            <%= link_to "Delete", favorite_path(favorite), {class: "btn btn-outline-warning", method: :delete} %>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%# <%= link_to "View", venue, {class:"btn btn-sm btn-outline-secondary"} %>
                <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
              </div>
              <!-- <small class="text-muted">9 mins</small> -->
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>
  </div>

</div>
</main>

<div class="a">

  <a class="center" href="#">Back to top</a>
</div>


    <%= yield %>
  </body>
</html>