config/routes.rb
Rails.application.routes.draw do

  resources :venues
  resources :users
  resources :bookings
  resources :favorites

  get 'partyspace', to: 'login#partyspace', as: 'partyspace'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'login#new', as: 'login'
  delete 'logout', to: 'login#destroy', as: 'logout'

  # get 'logout', to: 'login#destroy', as: 'logout'
  # delete '/logout', to: 'login#destroy', as: :logout

  resources :login, only: [:new, :create, :destroy]


  # root "venues#index"
  root "login#partyspace"

end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :bookings
  belongs_to :user

  validates :name, presence: true
  # validates :location, presence: true
  # validates :capacity, presence: true
  # validates :activity, length: {is:1}
  # validates :amenities, presence: true

  def self.sort_by_price
    Venue.all.sort_by {|venue| venue.price}
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  before_action :get_venue, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort_price]
      @venues = Venue.sort_by_price
    else
      @venues = Venue.all
    end
  end

  def show
    # byebug
  end

  def new
    @current_user
    @venue = Venue.new
  end

  def create
    params[:venue][:amenities] = params[:venue][:amenities][1..-1].to_json
    @venue = Venue.create(venue_params)
    if @venue.valid?
      redirect_to @venue
    else
      render :new
    end

  end

  def edit

  end

  def update
    @venue.amenities.clear
    params[:venue][:amenities] = params[:venue][:amenities][1..-1].join(", ")
    @venue.update(venue_params)
    if @venue.valid?
      redirect_to venue_path(@venue)
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to @current_user
  end

  private

  def get_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :location, :price, :capacity, :activity, :amenities, :img_url, :user_id)
  end

end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/edit.erb
<div class="a">
<h1>Edit <%= @venue.name %></h1>
<img src="<%= @venue.img_url %>" alt="<%= @venue.name %>" class="center">

<ul style="list-style-type:none;">
<%= form_for @venue do |f| %>
  <li><%= f.label :name %>
  <%= f.text_field :name %></li>
  <li><%= f.label :location %>
  <%= f.text_field :location %></li>
  <li><%= f.label :price %>
  <%= f.number_field :price %></li>
  <li><%= f.label :capacity %>
  <%= f.number_field :capacity %></li>
  <li><%= f.label :activity %>
  <%= f.collection_select :activity, @activities, :to_s, :to_s, include_blank: true %></li>

  <li><%= f.label :amenities %>
  <%= f.collection_check_boxes :amenities, @amenities, :to_s, :to_s, checked: @venue.amenities.split(",") %></li>


  <li><%= f.label :img_url %>
  <%= f.text_field :img_url %></li>

  <%= f.submit %>
<% end %>
</ul>
<%= link_to "Go back", venue_path %>
<br><br><br>

app/views/venues/index.erb
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="album.css" rel="stylesheet">
<div class="a">


<main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <%= link_to "view all", venues_path, {class: "btn btn-secondary btn-sm"} %>
        <span style="display:inline-block;width:15px"> </span>
        <%= form_tag("/venues", method: "get") do %>
          <input type="hidden" name="sort_price" value="yes">
          <%= submit_tag "price: low to high", {class: "btn btn-secondary btn-sm"} %>
        <% end %>
      </div>
    </section>



  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% @venues.each do |venue| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" src="<%= venue.img_url %>" </img><rect src="<%= venue.img_url %>"width="100%" height="100%" fill="#55595c"/>
            <div class="card-body">
              <p class="card-text"><%= venue.name %></p>
              <%= link_to "View Details", venue, {class:"btn btn-sm btn-outline-secondary"} %>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%# <%= link_to "View", venue, {class:"btn btn-sm btn-outline-secondary"} %>
                  <!-- <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button> -->
                </div>
                <!-- <small class="text-muted">9 mins</small> -->
              </div>
            </div>
          </div>
        </div>
        <% end %>



      </div>
    </div>
    <a href="#">Back to top</a>
  </div>
</div>
</main>

app/views/venues/new.erb
<div class="bgt">
  <div class="venue-list">


    <div class="a">
    <br>
      <h1>Create New Venue</h1>

      <ul style="list-style-type:none;">
        <% if @venue.errors.any? %>
          <% @venue.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        <% end %>

        <%= form_for @venue do |f| %>
          <li><%= f.label :name %>
          <%= f.text_field :name %></li>

          <li><%= f.label :location %>
          <%= f.text_field :location %></li>

          <li><%= f.label :price %>
          <%= f.number_field :price %></li>

          <li><%= f.label :capacity %>
          <%= f.number_field :capacity %></li>

          <li><%= f.label :activity %>
          <%= f.collection_select :activity, @activities, :to_s, :to_s, include_blank: true %></li>

          <li><%= f.label :amenities %>:
          <%= f.collection_check_boxes :amenities, @amenities, :to_s, :to_s, checked: @venue.amenities %></li>

          <li><%= f.label :img_url %>
          <%= f.text_field :img_url %></li>

          <input type="hidden" name="venue[user_id]" value="<%= @current_user.id %>">

          <%= f.submit "Post it!", {class: "btn btn-info"} %>
        <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/venues/show.erb
<div class="a">

  <section class="jumbotron text-center">
      <h1><%= @venue.name %></h1>
  </section>

  <img src="<%= @venue.img_url %>" alt="<%= @venue.name %>" class="center">
  <br>

<h5 class="center">
<ul style="list-style-type:none;">
  <li><b>Location: </b> <%= @venue.location %></li>
  <li><b>Price: </b> <%= number_to_currency(@venue.price) %> per hour</li>
  <li><b>Capacity: </b> <%= @venue.capacity %> people</li>
  <li><b>Activity: </b> <%= @venue.activity %></li>
  <li><b>Amenities: </b> <%= @venue.amenities.delete('"[]\"').split(",").join(", ") %></li>
  <li><b>Contact Host: </b><%= link_to @venue.user.name, @venue.user %></li>
</ul>

  </h5>
  <% if logged_in? %>
    <%= link_to "Book it", new_booking_path(venue_id: @venue.id), {class: "btn btn-outline-danger"}%>
    <%= link_to "Favorite it", new_favorite_path(venue_id: @venue.id), {class: "btn btn-outline-info"}%>
  <% else %>
    <%= link_to "Book it", login_path, {class: "btn btn-outline-danger"}%>
    <%= link_to "Favorite it", login_path, {class: "btn btn-outline-info"}%>
  <% end %>

<% if logged_in? && @current_user.id == @venue.user.id %>
<%= link_to "Edit", edit_venue_path(user_id: @current_user.id), {class: "btn btn-outline-success"} %>
<%= link_to "Delete", venue_path(@venue), {class: "btn btn-outline-warning", method: :delete} %>
<% end %>

</div>
<br><br><br>